import type { Metadata } from "next";
import { SITE } from "@/lib/site";
import { BLOG_POSTS } from "@/content/posts";
import { ArticleShell } from "@/components/ArticleShell";

const post = BLOG_POSTS.find((p) => p.slug === "compress-pdf-on-windows")!;

export const metadata: Metadata = {
  title: "How to Compress a PDF on Windows | CalmPDF",
    description:
        "Three ways to compress a PDF on Windows 10 and 11 — using Word, Microsoft Print to PDF, or a free private browser tool. No software install required.",
          keywords: [
              "compress pdf on windows",
                  "reduce pdf size windows",
                      "windows pdf compression",
                          "compress pdf windows 11",
                            ],
                              alternates: { canonical: `${SITE.url}/how-to/compress-pdf-on-windows` },
                                openGraph: {
                                    title: "How to Compress a PDF on Windows",
                                        description:
                                              "Three ways to shrink a PDF on Windows — including a free, private, browser-based option.",
                                                  url: `${SITE.url}/how-to/compress-pdf-on-windows`,
                                                      siteName: SITE.name,
                                                        },
                                                        };

                                                        export default function Page() {
                                                          return (
                                                              <ArticleShell post={post}>
                                                                    <h1 className="text-3xl font-semibold tracking-tight mb-4">
                                                                            How to Compress a PDF on Windows
                                                                                  </h1>
                                                                                        <p className="text-sage-700 mb-6">
                                                                                                Windows 10 and 11 don&apos;t ship with a dedicated PDF compressor, but you can still shrink a PDF without paying for Acrobat or installing third-party software. The three reliable options are Microsoft Word (if you have it), the built-in Microsoft Print to PDF driver, and a free browser-based tool like CalmPDF that runs entirely on your computer.
                                                                                                      </p>
                                                                                                      
                                                                                                            <h2 className="text-2xl font-semibold mt-8 mb-3">Method 1: Re-export from Microsoft Word</h2>
                                                                                                                  <p className="text-sage-700 mb-4">
                                                                                                                          If your PDF was originally a Word document — or if you can open it cleanly in Word — re-exporting with the &ldquo;Minimum size&rdquo; option is one of the fastest ways to reduce file size. Word downsamples embedded images and removes unused fonts in the process.
                                                                                                                                </p>
                                                                                                                                      <ol className="list-decimal list-inside space-y-2 text-sage-700 mb-4">
                                                                                                                                              <li>Open the PDF in Microsoft Word. Word will offer to convert it — accept the prompt.</li>
                                                                                                                                                      <li>Go to <strong>File &rarr; Save As</strong> and choose <strong>PDF</strong> as the file type.</li>
                                                                                                                                                              <li>Click <strong>Options</strong> and select <strong>Minimum size (publishing online)</strong>.</li>
                                                                                                                                                                      <li>Save with a new filename so you can compare against the original.</li>
                                                                                                                                                                            </ol>
                                                                                                                                                                                  <p className="text-sage-700 mb-6">
                                                                                                                                                                                          This works best for documents Word can interpret well — text-heavy reports, contracts, and resumes. Complex layouts, scanned PDFs, or forms with custom fonts may not survive the round-trip cleanly, so always check the result before sending it on.
                                                                                                                                                                                                </p>
                                                                                                                                                                                                
                                                                                                                                                                                                      <h2 className="text-2xl font-semibold mt-8 mb-3">Method 2: Print to Microsoft Print to PDF</h2>
                                                                                                                                                                                                            <p className="text-sage-700 mb-4">
                                                                                                                                                                                                                    Microsoft Print to PDF is a virtual printer included with Windows 10 and 11. Re-printing an existing PDF through it can sometimes shrink the file by stripping out metadata, embedded scripts, and orphaned objects.
                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                <ol className="list-decimal list-inside space-y-2 text-sage-700 mb-4">
                                                                                                                                                                                                                                        <li>Open the PDF in Microsoft Edge, Adobe Reader, or any PDF viewer.</li>
                                                                                                                                                                                                                                                <li>Press <strong>Ctrl + P</strong> to open the Print dialog.</li>
                                                                                                                                                                                                                                                        <li>In the printer dropdown, choose <strong>Microsoft Print to PDF</strong>.</li>
                                                                                                                                                                                                                                                                <li>Click <strong>Print</strong> and pick a save location.</li>
                                                                                                                                                                                                                                                                      </ol>
                                                                                                                                                                                                                                                                            <p className="text-sage-700 mb-6">
                                                                                                                                                                                                                                                                                    One caveat: Print to PDF rasterises pages in some viewers, which can actually <em>increase</em> file size for image-light documents. It is most useful when a PDF is bloated by structural overhead rather than image data.
                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                <h2 className="text-2xl font-semibold mt-8 mb-3">Method 3: Use CalmPDF in your browser</h2>
                                                                                                                                                                                                                                                                                                      <p className="text-sage-700 mb-4">
                                                                                                                                                                                                                                                                                                              CalmPDF runs entirely in your browser — there is nothing to install, and your file is never uploaded. It works on Windows 10 and 11 in Chrome, Edge, Firefox, and Brave, and the compression is consistent regardless of what created the original PDF.
                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                          <ol className="list-decimal list-inside space-y-2 text-sage-700 mb-6">
                                                                                                                                                                                                                                                                                                                                  <li>Open <strong>calmpdf.com/compress-pdf</strong> in your browser.</li>
                                                                                                                                                                                                                                                                                                                                          <li>Drag your PDF onto the page or click to select it.</li>
                                                                                                                                                                                                                                                                                                                                                  <li>Pick a compression level — <em>High quality</em> for a gentle reduction, <em>Smaller file</em> for a more aggressive one.</li>
                                                                                                                                                                                                                                                                                                                                                          <li>Click <strong>Compress</strong> and download the new PDF when it appears.</li>
                                                                                                                                                                                                                                                                                                                                                                </ol>
                                                                                                                                                                                                                                                                                                                                                                      <p className="text-sage-700 mb-6">
                                                                                                                                                                                                                                                                                                                                                                              Because compression happens locally, CalmPDF is a good fit for confidential documents — tax forms, contracts, medical records — that you would rather not hand off to a cloud service.
                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="text-2xl font-semibold mt-8 mb-3">Why CalmPDF</h2>
                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-sage-700 mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                        CalmPDF is free, requires no signup, and processes everything in your browser using JavaScript and pdf-lib. There is no upload, no email gate, and no watermark. If you close the tab, your file is gone — there is no copy on a server to forget about. That is especially useful on a Windows work machine where IT may already restrict installing PDF software.
                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                    <h2 className="text-2xl font-semibold mt-8 mb-3">Frequently asked questions</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="text-lg font-medium mt-5 mb-2">Does Windows 11 have a built-in PDF compressor?</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-sage-700 mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                        No. Windows 11 can create PDFs through Microsoft Print to PDF, but it has no dedicated &ldquo;reduce file size&rdquo; tool. You need either Microsoft Word, a third-party app, or a browser-based tool like CalmPDF.
                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 className="text-lg font-medium mt-5 mb-2">How much can I compress a PDF on Windows?</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-sage-700 mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  It depends on what is in the file. Image-heavy PDFs can typically be reduced by 60–80% without visibly hurting on-screen quality. Text-only PDFs are usually already small and may shrink by 5–15% at most.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3 className="text-lg font-medium mt-5 mb-2">Is it safe to compress sensitive PDFs online?</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-sage-700 mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Most online PDF compressors upload your file to a server, which is a real concern for anything sensitive. CalmPDF is different: it runs the compression in your browser, so the file never leaves your device. If you are unsure about a tool, check whether it explicitly says &ldquo;no upload&rdquo; or &ldquo;runs in your browser,&rdquo; and confirm in the browser network tab if you want to be certain.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </ArticleShell>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
